import { menu } from './components/menu';
import { promoSlider } from './components/slider';
import { productsSlider } from './components/slider';
import { mortgageCalculator } from './components/calculator';
import { autoCalculator } from './components/calculator';
import { creditCalculator } from './components/calculator';

menu.init();
promoSlider.init();
productsSlider.init();

mortgageCalculator.setCurrentData(`mortgage`);
mortgageCalculator.setCreditSumm(mortgageCalculator.currentData.creditSumm.min);
mortgageCalculator.setMinimumCreditSumm();
mortgageCalculator.setMaximumCreditSumm();
mortgageCalculator.setMinimumCreditPeriod();
mortgageCalculator.setMaximumCreditPeriod();
mortgageCalculator.setMinimumDownPaymentPersentage();
mortgageCalculator.setMinimumDownPayment();
mortgageCalculator.setCreditPeriod(mortgageCalculator.minimumCreditPeriod);
mortgageCalculator.setMinimumDownPaymentPersentage();
mortgageCalculator.calculateDownPayment(16);
mortgageCalculator.calculateDownPaymentPersentage();
mortgageCalculator.calculateCreditPersentage();
mortgageCalculator.calculateTotalCreditSumm();
mortgageCalculator.calculateAnnuityPayment();
mortgageCalculator.calculateMinimumIncome();
console.dir(mortgageCalculator);

autoCalculator.setCurrentData(`auto`);
autoCalculator.setCreditSumm(2000000);
autoCalculator.autoInsurance = true;
autoCalculator.lifeInsurance = true;
autoCalculator.setMinimumCreditSumm();
autoCalculator.setMaximumCreditSumm();
autoCalculator.setMinimumCreditPeriod();
autoCalculator.setMaximumCreditPeriod();
autoCalculator.setMinimumDownPaymentPersentage();
autoCalculator.setMinimumDownPayment();
autoCalculator.setCreditPeriod(autoCalculator.maximumCreditPeriod);
autoCalculator.setMinimumDownPaymentPersentage();
autoCalculator.calculateDownPayment(30);
autoCalculator.calculateDownPaymentPersentage();
autoCalculator.calculateCreditPersentage();
autoCalculator.calculateTotalCreditSumm();
autoCalculator.calculateAnnuityPayment();
autoCalculator.calculateMinimumIncome();
console.dir(autoCalculator);

creditCalculator.setCurrentData(`credit`);
creditCalculator.setCreditSumm(2000000);
creditCalculator.salaryProject = true;
creditCalculator.setMinimumCreditSumm();
creditCalculator.setMaximumCreditSumm();
creditCalculator.setMinimumCreditPeriod();
creditCalculator.setMaximumCreditPeriod();
creditCalculator.setCreditPeriod(creditCalculator.maximumCreditPeriod);
creditCalculator.calculateCreditPersentage();
creditCalculator.calculateTotalCreditSumm();
creditCalculator.calculateAnnuityPayment();
creditCalculator.calculateMinimumIncome();
console.dir(creditCalculator);
